ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  path: /
  hosts:
    - kibana.34.77.171.250.nip.io

nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
