---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: xom4ek/microservices-demo-frontend:1.0
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
